version: '2'
services:
  module:
    image: node:8.9.4
    command: yarn test
    working_dir: /home/node
    environment:
      - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
    volumes:
      - ./:/home/node
